[package]
name = "ba"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
nalgebra = "0.33.2"
thiserror = "2.0.3"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Zshare-generics=y"]

[toolchain]
channel = "nightly"
